name: icmlmaxr
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - gymnasium==0.29.1
      - gymnasium-robotics==1.2.4
      - pandas==2.2.1
      - py==1.11.0
      - pygame==2.5.2
      - stable-baselines3==2.2.1
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - tqdm==4.66.2
      - trio==0.25.0
      - wandb==0.16.4